name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main  


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build and Push Container
        run: |
          PROJECT_ID=$(echo "${{ secrets.GCP_PROJECT_ID }}" | tr -d '\n')
          IMAGE_NAME="europe-west1-docker.pkg.dev/${PROJECT_ID}/online-boutique/frontend:${{ github.sha }}"
          docker build -t "$IMAGE_NAME" ./src/frontend
          docker push "$IMAGE_NAME"

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: frontend
          region: ${{ secrets.GCP_REGION }}
          image: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/online-boutique/frontend:${{ github.sha }}

          env_vars: |
            PRODUCT_CATALOG_SERVICE_ADDR=localhost:8080
            CURRENCY_SERVICE_ADDR=localhost:8080
            CART_SERVICE_ADDR=localhost:8080
            RECOMMENDATION_SERVICE_ADDR=localhost:8080
            SHIPPING_SERVICE_ADDR=localhost:8080
            CHECKOUT_SERVICE_ADDR=localhost:8080
            AD_SERVICE_ADDR=localhost:8080
            PAYMENT_SERVICE_ADDR=localhost:8080
            EMAIL_SERVICE_ADDR=localhost:8080
            SHOPPING_ASSISTANT_SERVICE_ADDR=localhost:8080
          flags: "--allow-unauthenticated --port=8080"